# .github/workflows/ci.yml
name: Lint and Build Check

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install pnpm
        run: |
          npm install -g pnpm 
          echo "::add-path::$(npm bin -g)"

      - name: verify pnpm installation
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Run Build
        run: pnpm build
